services:
  - type: web
    name: resume-matcher
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONUTF8
        value: "1"
    healthCheckPath: /
    healthCheckPath: /
    autoDeploy: true
